### ISSUE TITLE
100MB 二进制纪念碑

### ISSUE THREAD

**Issue by foxwhite25** [YinY1/SimpleFS-rust#1]
创建了一个 100Mb 的空白 array ，编译器觉得是个 static reference，放到了最终可执行文件的 rodata 中，导致了神奇的二进制文件大小。

https://github.com/YinY1/SimpleFS-rust/blob/c8af514540748b36219318c10eeddabc1af8e2f3/simdisk/src/simple_fs.rs#L171

**Comment by YinY1** [comment]
神医！
